# GitHub Action Build and push Docker images - https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  SENTINEL_DASHBOARD_VERSION: 1.8.0
  RUN_JAVA_SH_VERSION: v1.3.8

jobs:
  
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate image tags
        run: |
          # Strip git ref prefix from version
          IMAGE_TAGS=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$IMAGE_TAGS" == "master" ] && IMAGE_TAGS=latest

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAGS="latest,$(echo $IMAGE_TAGS | sed -e 's/^v//')"

          # Set the `IMAGE_TAGS` environment variable
          echo ::set-env name=IMAGE_TAGS::$(echo $IMAGE_TAGS)

          echo $IMAGE_TAGS

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: build_version=${{ env.SENTINEL_DASHBOARD_VERSION }},run_java_sh_version=${{ env.RUN_JAVA_SH_VERSION }}
          repository: zhangfei9734/sentinel-dashboard
          tags: ${{ env.IMAGE_TAGS }}
          add_git_labels: true
          push: ${{ startsWith(github.ref, 'refs/tags/') || endsWith(github.ref, 'master') }}
